/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Gui;

import Datos.Cliente;
import Datos.Membresia;
import Datos.Registro;
import Datos.Video;
import Logica.ManejoClientes;
import Logica.ManejoMembresia;
import Logica.ManejoRegistros;
import Logica.ManejoVideo;
import java.awt.Point;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Andy
 */
public class JInternalFramerDevolucion extends javax.swing.JInternalFrame {

    ArrayList<Registro> lista;
    ManejoClientes manClientes = new ManejoClientes();
    ManejoVideo manVideo0 = new ManejoVideo();
    ManejoRegistros manReg = new ManejoRegistros();
    Cliente cliente;
    SimpleDateFormat df2 = new SimpleDateFormat("yyyy-MM-dd");
    Video video;
    Registro objAux;

    /**
     * Creates new form JInternalFramerDevolucion
     */
    public JInternalFramerDevolucion() {
        initComponents();
    }

    public void presentar() throws ClassNotFoundException {
        ArrayList<Registro> lstRegistro = new ArrayList();
        jTable1.removeAll();
        jTable1.setModel(new DefaultTableModel());
        Object columnas[] = {"IdRegistro", "Fecha Inicio", "Fecha Fin"};
        lstRegistro = manReg.cargarDatosPrestamoUnico(cliente.getIdPersona());
        DefaultTableModel modelo = new DefaultTableModel(null, columnas);
        jTable1.setModel(modelo);
        for (Registro registro : lstRegistro) {
            String NewValor[] = {String.valueOf(registro.getCodigoPrestamo()),
                String.valueOf(registro.getFechaRegistro()),
                String.valueOf(registro.getFechaDevolucion()),};
            modelo.addRow(NewValor);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextFieldCedula = new javax.swing.JTextField();
        jButtonBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButtonDevolver = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldmulta = new javax.swing.JTextField();

        jLabel1.setText("Cedula:");

        jButtonBuscar.setText("BUSCAR");
        jButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "idPrestamo", "Fecha Registro", "Fecha Devolucion"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButtonDevolver.setText("Devolver");
        jButtonDevolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDevolverActionPerformed(evt);
            }
        });

        jLabel2.setText("Multa:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(37, 37, 37)
                            .addComponent(jTextFieldCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(81, 81, 81)
                            .addComponent(jButtonBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jButtonDevolver)
                            .addGap(79, 79, 79)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(58, 58, 58)
                        .addComponent(jTextFieldmulta, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldmulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(jButtonDevolver)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed
        try {
            // TODO add your handling code here:
            cliente = manClientes.CargarPersonaTxt(Integer.parseInt(jTextFieldCedula.getText()));
            presentar();
            lista = manReg.cargarDatosPrestamoUnico(cliente.getIdPersona());

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(JInternalFramerDevolucion.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonBuscarActionPerformed

    private void jButtonDevolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDevolverActionPerformed
        try {
            // TODO add your handling code here:

            manReg.realizarDev(objAux);
            JOptionPane.showMessageDialog(null, "Devolucion hecha");
            presentar();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(JInternalFramerDevolucion.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButtonDevolverActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        Date fechaDev = new Date();
        Point point = evt.getPoint();
        int row = jTable1.rowAtPoint(point);

        if (evt.getClickCount() == 1) {
            for (Registro ListaPrestamo : lista) {
                if (Integer.parseInt((String) jTable1.getValueAt(row, 0)) == ListaPrestamo.getCodigoPrestamo()) {
                    objAux = ListaPrestamo;
                    if (manReg.verificaDevolucion(objAux, fechaDev) == 1) {
                        jTextFieldmulta.setText("0");
                    } else {
                        for (Video listaV : ListaPrestamo.getListaVideos()) {
                            jTextFieldmulta.setText(String.valueOf(listaV.getPrecioRenta() * 0.05));
                        }

                    }
                }
            }

        }
    }//GEN-LAST:event_jTable1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JButton jButtonDevolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldCedula;
    private javax.swing.JTextField jTextFieldmulta;
    // End of variables declaration//GEN-END:variables
}
