/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Gui;

import Datos.Reg_Acc;
import Datos.Video;
import Logica.ManejoAcceso;
import Logica.ManejoVideo;
import java.awt.Point;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Andy
 */
public class JInternalFrameReporteAccesos extends javax.swing.JInternalFrame {

    ManejoAcceso manAcc = new ManejoAcceso();
    ManejoVideo manVid = new ManejoVideo();
    ArrayList<Reg_Acc> lstAccesos;
    Video objAux;
    static int tipo;

    /**
     * Creates new form JInternalFrameReporteVideos
     */
    public JInternalFrameReporteAccesos() {
        initComponents();

        try {

            presentar();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(JInternalFrameReporteAccesos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void presentar() throws ClassNotFoundException {
        lstAccesos = new ArrayList();
        jTable1.removeAll();
        jTable1.setModel(new DefaultTableModel());
        Object columnas[] = {"ID", "NOMBRE", "ENTRAD", "SALIDA"};
        lstAccesos = manAcc.CargarMaterialesTxt();
        DefaultTableModel modelo = new DefaultTableModel(null, columnas);
        jTable1.setModel(modelo);
        for (Reg_Acc reg_Acc : lstAccesos) {
            String NewValor[] = {String.valueOf(reg_Acc.getId_Acc()),
                String.valueOf(reg_Acc.getNombre()),
                String.valueOf(reg_Acc.getEntrada()),
                String.valueOf(reg_Acc.getSalida())
            };
            modelo.addRow(NewValor);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 813, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 42, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked

    }//GEN-LAST:event_jTable1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
