/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Gui;

import Datos.Cliente;
import Datos.Constantes;
import Datos.Membresia;
import Datos.Registro;
import Datos.Video;
import Logica.ManejoClientes;
import Logica.ManejoMembresia;
import Logica.ManejoRegistros;
import Logica.ManejoVideo;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Andy
 */
public class JInternalFrameRegistroCliente extends javax.swing.JInternalFrame {

    ManejoClientes manClientes = new ManejoClientes();
    ManejoMembresia manMemb = new ManejoMembresia();
    ManejoVideo manVideo0 = new ManejoVideo();
    ManejoRegistros manReg = new ManejoRegistros();
    Membresia membresia;
    static Cliente cliente;
    SimpleDateFormat df2 = new SimpleDateFormat("yyyy-MM-dd");
    Video video;

    /**
     * Creates new form JInternalFrameRegistro
     */
    public JInternalFrameRegistroCliente() {
        initComponents();
        jTextFieldRenta.setVisible(false);
        jLabelRenta.setVisible(false);
        jTextFieldVenta.setVisible(false);
        jLabelVenta.setVisible(false);
        membresia = manMemb.CargarMembresiaTxt(cliente.getIdMembresia());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        jComboBoxrEGISTRO = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextFieldBuscarTitulo = new javax.swing.JTextField();
        jButtonBuscarpeli = new javax.swing.JButton();
        jLabelRenta = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jTextFieldActor = new javax.swing.JTextField();
        jTextFieldtitulo = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jTextFieldVenta = new javax.swing.JTextField();
        jTextFieldDirector = new javax.swing.JTextField();
        jTextFieldRenta = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jTextFieldCantidad = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabelVenta = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel21 = new javax.swing.JLabel();
        jTextFieldAnio = new javax.swing.JTextField();
        jTextFieldGENERO = new javax.swing.JTextField();
        jButtonRegistro = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        jTextFieldPrecioTotal = new javax.swing.JTextField();

        jLabel9.setText("PELICULAS.");

        jComboBoxrEGISTRO.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "VENTA", "PRESTAMO" }));
        jComboBoxrEGISTRO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxrEGISTROActionPerformed(evt);
            }
        });

        jLabel11.setText("Venta/Prestamo");

        jLabel12.setText("Titulo:");

        jButtonBuscarpeli.setText("BUSCAR PELICULA");
        jButtonBuscarpeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarpeliActionPerformed(evt);
            }
        });

        jLabelRenta.setText("Valor Renta:");

        jLabel14.setText("Cantidad:");

        jLabel15.setText("Titulo");

        jTextFieldActor.setEditable(false);
        jTextFieldActor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldActorKeyTyped(evt);
            }
        });

        jTextFieldtitulo.setEditable(false);

        jLabel16.setText("Director:");

        jTextFieldVenta.setEditable(false);
        jTextFieldVenta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldVentaKeyTyped(evt);
            }
        });

        jTextFieldDirector.setEditable(false);
        jTextFieldDirector.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldDirectorKeyTyped(evt);
            }
        });

        jTextFieldRenta.setEditable(false);
        jTextFieldRenta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldRentaKeyTyped(evt);
            }
        });

        jLabel17.setText("Genero:");

        jTextFieldCantidad.setEditable(false);
        jTextFieldCantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldCantidadKeyTyped(evt);
            }
        });

        jLabel18.setText("Actor:");

        jLabel19.setText("Año:");

        jLabelVenta.setText("Valor Venta:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "TODO", "TITULO", "GENERO" }));

        jLabel21.setText("BUACAR POR:");

        jTextFieldAnio.setEditable(false);

        jTextFieldGENERO.setEditable(false);

        jButtonRegistro.setText("COMPRAR");
        jButtonRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegistroActionPerformed(evt);
            }
        });

        jLabel22.setText("Precio:");

        jTextFieldPrecioTotal.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(130, 130, 130)
                    .addComponent(jTextFieldBuscarTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(279, Short.MAX_VALUE))
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel15)
                        .addComponent(jLabel16)
                        .addComponent(jLabel17)
                        .addComponent(jLabel18))
                    .addGap(47, 47, 47)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jTextFieldGENERO, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                        .addComponent(jTextFieldDirector, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTextFieldtitulo)
                        .addComponent(jTextFieldActor))
                    .addGap(67, 67, 67)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jButtonBuscarpeli)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabelRenta)
                                .addComponent(jLabel14)
                                .addComponent(jLabel19)
                                .addComponent(jLabelVenta)
                                .addComponent(jLabel22))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTextFieldVenta, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jTextFieldRenta, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jTextFieldCantidad, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jTextFieldAnio, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jButtonRegistro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                                .addComponent(jTextFieldPrecioTotal)))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel11)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jComboBoxrEGISTRO, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(32, 32, 32)))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(190, 190, 190)
                        .addComponent(jLabel9))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel21)
                                .addGap(80, 80, 80)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jTextFieldBuscarTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonBuscarpeli))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jComboBoxrEGISTRO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(jTextFieldtitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(jTextFieldDirector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(jTextFieldGENERO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(jTextFieldActor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(jTextFieldAnio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelVenta)
                            .addComponent(jTextFieldVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelRenta)
                            .addComponent(jTextFieldRenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(jTextFieldCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(jTextFieldPrecioTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonRegistro)
                .addGap(163, 163, 163))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldActorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldActorKeyTyped
        // TODO add your handling code here:
        char tecla;
        tecla = evt.getKeyChar();
        if (!Character.isLetter(tecla) && tecla != KeyEvent.VK_SPACE && tecla != KeyEvent.VK_BACK_SPACE) {
            evt.consume();
            getToolkit().beep();
        }
    }//GEN-LAST:event_jTextFieldActorKeyTyped

    private void jTextFieldVentaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldVentaKeyTyped
        // TODO add your handling code here:
        char tecla;
        tecla = evt.getKeyChar();
        if (!Character.isDigit(tecla) && tecla != KeyEvent.VK_BACK_SPACE) {
            evt.consume();
            getToolkit().beep();
        }
    }//GEN-LAST:event_jTextFieldVentaKeyTyped

    private void jTextFieldDirectorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldDirectorKeyTyped
        // TODO add your handling code here:
        char tecla;
        tecla = evt.getKeyChar();
        if (!Character.isLetter(tecla) && tecla != KeyEvent.VK_SPACE && tecla != KeyEvent.VK_BACK_SPACE) {
            evt.consume();
            getToolkit().beep();
        }
    }//GEN-LAST:event_jTextFieldDirectorKeyTyped

    private void jTextFieldRentaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldRentaKeyTyped
        // TODO add your handling code here:
        char tecla;
        tecla = evt.getKeyChar();
        if (!Character.isDigit(tecla) && tecla != KeyEvent.VK_BACK_SPACE) {
            evt.consume();
            getToolkit().beep();
        }
    }//GEN-LAST:event_jTextFieldRentaKeyTyped

    private void jTextFieldCantidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldCantidadKeyTyped
        // TODO add your handling code here:
        char tecla;
        tecla = evt.getKeyChar();
        if (!Character.isDigit(tecla) && tecla != KeyEvent.VK_BACK_SPACE) {
            evt.consume();
            getToolkit().beep();
        }
    }//GEN-LAST:event_jTextFieldCantidadKeyTyped

    private void jButtonBuscarpeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarpeliActionPerformed
        // TODO add your handling code here:
        video = manVideo0.CargarVideoTxt(jTextFieldBuscarTitulo.getText());
        if (video != null) {
            jTextFieldtitulo.setText(video.getTitulo());
            jTextFieldDirector.setText(video.getDirector());
            jTextFieldGENERO.setText(video.getGenero());
            jTextFieldActor.setText(video.getActor());
            jTextFieldAnio.setText(String.valueOf(video.getAnio()));
            jTextFieldRenta.setText(String.valueOf(video.getPrecioRenta()));
            jTextFieldVenta.setText(String.valueOf(video.getPrecioVenta()));
            jTextFieldCantidad.setText(String.valueOf(video.getCantidad()));
            if (jComboBoxrEGISTRO.getSelectedIndex() == 0) {
                jTextFieldPrecioTotal.setText(String.valueOf(manReg.calcularPrecio(
                        video.getPrecioVenta(), membresia.getDescuento())));
            } else {
                jTextFieldPrecioTotal.setText(String.valueOf(manReg.calcularPrecio(
                        video.getPrecioRenta(), membresia.getDescuento())));
            }

        } else {
            JOptionPane.showMessageDialog(null, "No existe el video");
            jTextFieldtitulo.setText("");
        }


    }//GEN-LAST:event_jButtonBuscarpeliActionPerformed

    private void jButtonRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegistroActionPerformed
        // TODO add your handling code here:
        ArrayList<Video> list = new ArrayList<>();
        Constantes consta = new Constantes();
        Registro registro = new Registro();
        Date fechaSistema = new Date();
        registro.setFechaRegistro(fechaSistema);
        registro.setCliente(cliente);
        list.add(video);
        registro.setListaVideos(list);
        if (jComboBoxrEGISTRO.getSelectedIndex() == 0) {
            try {
                registro.setFechaDevolucion(fechaSistema);
                registro.setDiasPrestamo(0);
                registro.setTipo(0);
                registro.setEstado(0);
                manReg.InsertarPrestamo(registro);
                JOptionPane.showMessageDialog(null, "VENTA GUARDADO");

            } catch (ClassNotFoundException ex) {
                Logger.getLogger(JInternalFrameRegistroCliente.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(JInternalFrameRegistroCliente.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            try {
                registro.setDiasPrestamo(consta.getDiasPrestamo());
                registro.setFechaDevolucion(manReg.calcularFecha(fechaSistema));
                registro.setTipo(1);
                registro.setEstado(1);
                manReg.InsertarPrestamo(registro);
                JOptionPane.showMessageDialog(null, "PRESTAMO GUARDADO");
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(JInternalFrameRegistroCliente.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(JInternalFrameRegistroCliente.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
        jTextFieldBuscarTitulo.setText("");
        jTextFieldtitulo.setText("");
        jTextFieldDirector.setText("");
        jTextFieldGENERO.setText("");
        jTextFieldActor.setText("");
        jTextFieldAnio.setText("");
        jTextFieldRenta.setText("");
        jTextFieldVenta.setText("");
        jTextFieldCantidad.setText("");
        jTextFieldPrecioTotal.setText("");

    }//GEN-LAST:event_jButtonRegistroActionPerformed

    private void jComboBoxrEGISTROActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxrEGISTROActionPerformed
        // TODO add your handling code here:
        if (jComboBoxrEGISTRO.getSelectedIndex() == 0) {
            jTextFieldVenta.setVisible(true);
            jLabelVenta.setVisible(true);
            jTextFieldRenta.setVisible(false);
            jLabelRenta.setVisible(false);
            jButtonRegistro.setText("VENDER");
            jTextFieldPrecioTotal.setText(String.valueOf(manReg.calcularPrecio(
                    video.getPrecioVenta(), membresia.getDescuento())));

        } else {
            jTextFieldVenta.setVisible(false);
            jLabelVenta.setVisible(false);
            jTextFieldRenta.setVisible(true);
            jLabelRenta.setVisible(true);
            jButtonRegistro.setText("RENTAR");
            jTextFieldPrecioTotal.setText(String.valueOf(manReg.calcularPrecio(
                    video.getPrecioRenta(), membresia.getDescuento())));
        }
    }//GEN-LAST:event_jComboBoxrEGISTROActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBuscarpeli;
    private javax.swing.JButton jButtonRegistro;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBoxrEGISTRO;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelRenta;
    private javax.swing.JLabel jLabelVenta;
    private javax.swing.JTextField jTextFieldActor;
    private javax.swing.JTextField jTextFieldAnio;
    private javax.swing.JTextField jTextFieldBuscarTitulo;
    private javax.swing.JTextField jTextFieldCantidad;
    private javax.swing.JTextField jTextFieldDirector;
    private javax.swing.JTextField jTextFieldGENERO;
    private javax.swing.JTextField jTextFieldPrecioTotal;
    private javax.swing.JTextField jTextFieldRenta;
    private javax.swing.JTextField jTextFieldVenta;
    private javax.swing.JTextField jTextFieldtitulo;
    // End of variables declaration//GEN-END:variables
}
