/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Gui;

import Datos.Administrador;
import Datos.Cliente;
import Datos.Constantes;
import Datos.Vendedor;
import Logica.ManejoAcceso;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author salas
 */
public class Logeo extends javax.swing.JFrame {

    ManejoAcceso manAceso = new ManejoAcceso();
    Constantes Parametro = new Constantes();
    int numeroVeces = 0;
    int rol;

    /**
     * Creates new form main
     */
    public Logeo() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextUsuario = new javax.swing.JTextField();
        jTextRespuesta = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBoxPersona = new javax.swing.JComboBox();
        jButtoniNGRESO = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jTextClave = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextUsuario.setText(" ");

        jLabel1.setText("Usuario:");

        jLabel2.setText("Clave:");

        jComboBoxPersona.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ADMINISTRADOR", "VENDEDOR", "CLIENTE" }));
        jComboBoxPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxPersonaActionPerformed(evt);
            }
        });

        jButtoniNGRESO.setText("INGRESAR");
        jButtoniNGRESO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtoniNGRESOActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setText("INGRESO AL SISTEMA.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                            .addComponent(jTextClave))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jComboBoxPersona, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtoniNGRESO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jTextRespuesta, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(165, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(145, 145, 145)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBoxPersona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jButtoniNGRESO)
                    .addComponent(jTextClave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextRespuesta, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxPersonaActionPerformed
        // TODO add your handling code here:

        switch (jComboBoxPersona.getSelectedIndex()) {
            case 0:
                rol = 0;

                break;
            case 1:
                rol = 1;
                break;
            case 2:
                rol = 2;
                break;
            default:
                break;

        }

    }//GEN-LAST:event_jComboBoxPersonaActionPerformed

    private void jButtoniNGRESOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtoniNGRESOActionPerformed
        // TODO add your handling code here:
        Object obj;
        if (numeroVeces < Parametro.getNumeroIntentos()) {
            try {
                obj = manAceso.ValidarCamposIngreso(jTextUsuario.getText(),
                        jTextClave.getText(), rol);
                if (obj != null) {
                    switch (rol) {
                        case 0:
                            PrincipalAdministrador.administrador=(Administrador)obj;
                            PrincipalAdministrador princAdmin=new PrincipalAdministrador();
                            princAdmin.setVisible(true);
                            Logeo.this.dispose();
                            break;
                        case 1:
                            PrincipalVendedor.vendedor=(Vendedor)obj;
                            PrincipalVendedor princVend=new PrincipalVendedor();
                            princVend.setVisible(true);
                            Logeo.this.dispose();
                            break;
                        case 2:
                            PrincipalCliente.cliente=(Cliente)obj;
                            PrincipalCliente princCliente=new PrincipalCliente();
                            princCliente.setVisible(true);
                            Logeo.this.dispose();
                            break;
                        default:
                            break;
                    }

                } else {
                    numeroVeces++;
                    JOptionPane.showConfirmDialog(null, "Usuario o clave incorrecta\nIntento:" + numeroVeces, "ACCESO DENEGADO", JOptionPane.YES_OPTION);

                }
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(Logeo.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(Logeo.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            jTextRespuesta.setText("Numero de intentos Superados");
            Logeo.this.dispose();
        }
    }//GEN-LAST:event_jButtoniNGRESOActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Logeo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Logeo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Logeo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Logeo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Logeo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtoniNGRESO;
    private javax.swing.JComboBox jComboBoxPersona;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField jTextClave;
    private javax.swing.JTextField jTextRespuesta;
    private javax.swing.JTextField jTextUsuario;
    // End of variables declaration//GEN-END:variables
}
